تفاوت بین آرایه های
numpy
و 
python

In [71]:
import numpy as np
import time

In [2]:
a = np.random.random(10000000)
print(len(a))
print(type(a))
print(a[0:10])

10000000
<class 'numpy.ndarray'>
[0.4465869  0.33410264 0.83792756 0.97971594 0.37088951 0.62890137
 0.19862088 0.75593195 0.24494061 0.29593638]


In [3]:
t=time.time()
sum = 0
for i in range(len(a)):
    sum += a[i]
print(time.time() - t)
print(sum)

4.976911783218384
4999587.771509823


In [4]:
t = time.time()
sum = np.sum(a)
print(time.time() - t)
print(sum)

0.018990755081176758
4999587.771508797


________________________________________________________________________________
تایپ های مختلف داده در پایتون
________________________________________________________________________________

In [2]:
#one 
a=2
print(type(a))

<class 'int'>


In [4]:
b = 2.5
print(type(b))

<class 'float'>


In [8]:
a = float(5)
print(a)
print(type(a))

5.0
<class 'float'>


In [9]:
a = "hello world"
print(a)
print(type(a))

hello world
<class 'str'>


In [60]:
print("print")

print


In [10]:
a = True
print(type(a))

<class 'bool'>


In [62]:
a= (5 ,6)
print(type(a))

<class 'tuple'>


In [64]:
# a[0]
a[0]=8

TypeError: 'tuple' object does not support item assignment

In [19]:
a=("python" , (2, 6))
print(a)
print(a[0])
print(a[1] + a[2])

('python', 2, 6)
python
8


لطفا یک تاپل تک عضوی درست کنید

In [65]:
a=tuple(5)

TypeError: 'int' object is not iterable

In [20]:
a = (5 ,)

In [67]:
a = (1 , 3 ,5,7 ,9)
print(a[-2])

7


In [68]:
print(min(a))
print(max(a))
print(sum(a))
print(len(a))

1
9
25
5


In [70]:
a=[1 ,3 ,5 ,7 ,9]
print(type(a))

<class 'list'>


In [30]:
print(a[0])
print(a[-1])

1
9


In [31]:
print(min(a))
print(max(a))
print(sum(a))
print(len(a))

1
9
25
5


In [33]:
a[2] = 12
print(a)

[1, 3, 12, 7, 9]


In [37]:
a = {"name": "mohamad" , "age": 32}
print(type(a))
print(a)

<class 'dict'>
{'name': 'mohamad', 'age': 32}


In [39]:
a = {"name": ["mohamad" , "ali" , "reza" ] , "age": [32 , 34 , 36]}
print(a)

{'name': ['mohamad', 'ali', 'reza'], 'age': [32, 34, 36]}


In [40]:
a['name']

['mohamad', 'ali', 'reza']

In [41]:
a.keys()

dict_keys(['name', 'age'])

________________________________________________________________________________
ایجاد آرایه
________________________________________________________________________________

In [5]:
numpy_array = np.array([1 , 2 , 3 , 4 , 5])
numpy_array_string = np.array(['1' , '2' , '3' , '4' , '5'])
print(numpy_array)
print(numpy_array_string)

[1 2 3 4 5]
['1' '2' '3' '4' '5']


In [6]:
print(len(numpy_array))
print(len(numpy_array_string))
print(numpy_array[0])
print(numpy_array_string[0])


5
5
1
1


In [7]:
print(np.sum(numpy_array))

15


In [8]:
print(np.sum(numpy_array_string))

TypeError: cannot perform reduce with flexible type

In [9]:
arr=[6,7,8,9,10]
np_arr=np.array(arr)
print(np_arr)
print(type(np_arr))

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


ایجاد آرایه دو بعدی

In [10]:
numpy_2D_array = np.array([[1 ,2 ,3 ],[4 ,5 ,6 ]])

In [11]:
print(numpy_2D_array)
print("_____________")
print(numpy_2D_array[0])
print("_____________")
print(numpy_2D_array[1])

[[1 2 3]
 [4 5 6]]
_____________
[1 2 3]
_____________
[4 5 6]


In [12]:
print(numpy_2D_array.shape)
print(numpy_array.shape)

(2, 3)
(5,)


In [13]:
print(np.sum(numpy_2D_array[0]))
print(np.sum(numpy_2D_array[1]))
print(np.sum(numpy_2D_array))

6
15
21


ایجاد آرایه سه بعدی

In [14]:
numpy_3D_array = np.array([[1, 2, 3],[4 ,5 ,6 ],[7 ,8 ,9 ]])

In [15]:
print(numpy_3D_array.shape)

(3, 3)


In [16]:
print(np.sum(numpy_3D_array[2][1]))

8


استفاده از رنج برای درست کردن آرایه

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
np.arange(10,-11,-1)

array([ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,
        -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [45]:
z = np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [46]:
print(z[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [47]:
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

ساخت آرایه تمام صفر و تمام یک

In [22]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [23]:
a = np.zeros(5)
a[1]=5
print(a)

[0. 5. 0. 0. 0.]


تغیر شکل در آرایه

In [24]:
arr=np.arange(20)
arr_4_in_5= arr.reshape(5,4)
print(arr_4_in_5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [25]:
arr_4_in_5= arr.reshape(1,4,5)
print(arr_4_in_5)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [26]:
arr_reshape_1D=arr_4_in_5.reshape(20)
print(arr_reshape_1D)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
arr_reshape=arr_4_in_5.reshape(5,2,2)
print(arr_reshape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


تخت کردن آرایه 

In [28]:
print(numpy_2D_array.flatten())
print(arr_reshape.flatten())

[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


چسباندن آرایه ها به صورت عمودی ، افقی 

In [29]:
a= np.array([[0,1,2],[3,4,5],[6,7,8]])
b= np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.vstack((a,b)))
print("__________")
print(np.hstack((a,b)))
print("__________")

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
__________
[[0 1 2 9 8 7]
 [3 4 5 6 5 4]
 [6 7 8 3 2 1]]
__________


In [30]:
a =np.zeros(5)
b = np.ones(5)
print(np.hstack((a,b)))
print(np.hstack((b,a)))

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


ایجاد ترانهاده یک آرایه چند بعدی

In [31]:
print(numpy_2D_array)
print(np.transpose(numpy_2D_array))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [32]:
print(numpy_3D_array)
print(np.transpose(numpy_3D_array))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


پیمایش آرایه

In [33]:
big_arr=np.array(np.arange(20))

In [34]:
big_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
for i in big_arr:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [36]:
big_2d_arr = big_arr.reshape(10,2)

In [37]:
for i in big_2d_arr:
    for x in i:
        print (x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [38]:
for i in np.nditer(big_2d_arr):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [39]:
for x in np.nditer(big_2d_arr[:, ::2]):
    print(x)

0
2
4
6
8
10
12
14
16
18


In [40]:
for idx, x in np.ndenumerate(big_2d_arr):
    print(idx, x)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9
(5, 0) 10
(5, 1) 11
(6, 0) 12
(6, 1) 13
(7, 0) 14
(7, 1) 15
(8, 0) 16
(8, 1) 17
(9, 0) 18
(9, 1) 19


ایجاد اعداد تصادفی با استفاده از 
numpy

In [41]:
arr_random = np.random.rand(5)
arr_random_2d=np.random.rand(5,2)
print(arr_random)
print(arr_random_2d)

[0.04535675 0.99759836 0.87948301 0.77909245 0.00673335]
[[0.57156848 0.5616647 ]
 [0.48503863 0.78640035]
 [0.68786215 0.1777579 ]
 [0.61472175 0.91345274]
 [0.86371733 0.16158488]]


In [42]:
loc = 0.0 #Mean (“centre”) of the distribution
scal = 1.0 #Standard deviation (spread or “width”) of the distribution. Must be non-negative. 
size = 5 #Output shape
array = np.random.normal(0.0, 1.0, 5) 
print(array)
print("_____________")
array = np.random.normal(0.0, 1.0, (2,10)) 
print(array)

[ 1.05337541  0.8185792   1.55876133 -0.38638043 -0.08669769]
_____________
[[ 0.17452445 -0.69955819 -0.12820754 -0.42799095  0.86817621  1.71049245
   0.97509972  2.23492368 -1.51957547 -0.53663249]
 [ 1.22226481  1.16478586  1.62274696 -0.6281412   0.38816702 -1.30525845
   1.17423107 -1.17908668  0.66848104  0.83882004]]


کار با تاریخ در numpy

In [43]:
today = np.datetime64('2021-06-09')
print(np.datetime64(today, 'Y'))
print(np.datetime64(today, 'M'))
print(np.datetime64(today, 'D'))

2021
2021-06
2021-06-09


In [44]:
dates = np.arange('2021-02', '2021-03', dtype='datetime64[D]') 
print(dates)

['2021-02-01' '2021-02-02' '2021-02-03' '2021-02-04' '2021-02-05'
 '2021-02-06' '2021-02-07' '2021-02-08' '2021-02-09' '2021-02-10'
 '2021-02-11' '2021-02-12' '2021-02-13' '2021-02-14' '2021-02-15'
 '2021-02-16' '2021-02-17' '2021-02-18' '2021-02-19' '2021-02-20'
 '2021-02-21' '2021-02-22' '2021-02-23' '2021-02-24' '2021-02-25'
 '2021-02-26' '2021-02-27' '2021-02-28']


In [45]:
dur = np.datetime64('2021-01-01') - np.datetime64('2020-01-01') 
print(dur)
print(np.timedelta64(dur, 'W'))

366 days
52 weeks


In [46]:
calendar = np.arange('2021-01' , '2022-01' ,  dtype='datetime64[D]')
print(type(calendar))
print(len(calendar))
print(calendar)

<class 'numpy.ndarray'>
365
['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31' '2021-02-01' '2021-02-02' '2021-02-03' '2021-02-04'
 '2021-02-05' '2021-02-06' '2021-02-07' '2021-02-08' '2021-02-09'
 '2021-02-10' '2021-02-11' '2021-02-12' '2021-02-13' '2021-02-14'
 '2021-02-15' '2021-02-16' '2021-02-17' '2021-02-18' '2021-02-19'
 '2021-02-20' '2021-02-21' '2021-02-22' '2021-02-23' '2021-02-24'
 '2021-02-25' '2021-02-26' '2021-02-27' '2021-02-28' '2021-03-01'
 '2021-03-02' '2021-03-03' '2021-03-04' '2021-03-05' '2021-03-06'
 '2021-03-07' '2021-03-08' '2021-03-09' '2021-03-10' '2021-03-11'
 '2021-03-12' '2021-03-13' '2021-03-14' '2021-03

In [47]:
a = np.linspace(0, 1000, num=10)
print(a)
print("________________")
b = np.linspace(-2*np.pi, 2*np.pi, 100)
print(b)

[   0.          111.11111111  222.22222222  333.33333333  444.44444444
  555.55555556  666.66666667  777.77777778  888.88888889 1000.        ]
________________
[-6.28318531 -6.15625227 -6.02931923 -5.9023862  -5.77545316 -5.64852012
 -5.52158709 -5.39465405 -5.26772102 -5.14078798 -5.01385494 -4.88692191
 -4.75998887 -4.63305583 -4.5061228  -4.37918976 -4.25225672 -4.12532369
 -3.99839065 -3.87145761 -3.74452458 -3.61759154 -3.4906585  -3.36372547
 -3.23679243 -3.10985939 -2.98292636 -2.85599332 -2.72906028 -2.60212725
 -2.47519421 -2.34826118 -2.22132814 -2.0943951  -1.96746207 -1.84052903
 -1.71359599 -1.58666296 -1.45972992 -1.33279688 -1.20586385 -1.07893081
 -0.95199777 -0.82506474 -0.6981317  -0.57119866 -0.44426563 -0.31733259
 -0.19039955 -0.06346652  0.06346652  0.19039955  0.31733259  0.44426563
  0.57119866  0.6981317   0.82506474  0.95199777  1.07893081  1.20586385
  1.33279688  1.45972992  1.58666296  1.71359599  1.84052903  1.96746207
  2.0943951   2.22132814  2.34826118 

In [48]:
print(np.arange(-10,12,2))

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [49]:
print(np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


___________________
محاسبه رادیکال
___________________

In [50]:
a= np.arange(10)

In [51]:
print(np.sqrt(a))
print("_____________")
print(np.sqrt([4 , -3 , -5+4j]))
print("_____________")
print(np.sqrt([np.inf]))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
_____________
[2.        +0.j         0.        +1.73205081j 0.83759305+2.3877944j ]
_____________
[inf]


___________________
تابع نمایی
___________________

In [52]:
print(np.exp(a))
print("__________")
print(np.expm1(a))
print("__________")
print(np.exp2(a))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
__________
[0.00000000e+00 1.71828183e+00 6.38905610e+00 1.90855369e+01
 5.35981500e+01 1.47413159e+02 4.02428793e+02 1.09563316e+03
 2.97995799e+03 8.10208393e+03]
__________
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


___________________________________
تقسیم یک عدد به قسمت اعشاری و غیر اعشاری
___________________________________

In [53]:
a=np.random.rand(10) *10
print(a)
print("___________________")
print(np.modf(a))

[6.62521964 7.0170386  4.11674808 1.93428253 6.92882268 2.69696252
 8.71058745 4.68502356 5.51196632 5.98772949]
___________________
(array([0.62521964, 0.0170386 , 0.11674808, 0.93428253, 0.92882268,
       0.69696252, 0.71058745, 0.68502356, 0.51196632, 0.98772949]), array([6., 7., 4., 1., 6., 2., 8., 4., 5., 5.]))


In [54]:
print(np.modf(np.random.rand(20)*10)[1])

[0. 4. 1. 0. 7. 3. 5. 2. 5. 9. 7. 6. 3. 4. 5. 8. 1. 9. 0. 9.]


_______________________
دستور where
_______________________

In [55]:
b = np.arange(20)
print(np.where(b<5))

(array([0, 1, 2, 3, 4], dtype=int64),)


In [56]:
print(np.where(b<5,b,0))
print("__________")
print(np.where(b>10 , b,np.sqrt(b)))

[0 1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
__________
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.          3.16227766 11.
 12.         13.         14.         15.         16.         17.
 18.         19.        ]


In [57]:
c=[]
for i in b:
    if i<5:
        c.append(i)
    else:
        c.append(0)
c = np.array(c)
print(c)

[0 1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [58]:
a = np.random.rand(100)*100
print(np.where(a>80 , a,a*10))

[ 84.42992128 268.55218577  54.09210881  49.43978484 698.48205195
 531.61881633 136.96346763 485.33872148  86.03908942 483.39255414
  87.10132681 656.16541177 152.4046096   90.96069734  95.07320825
 474.18015279 201.4620085  114.89503197 257.68637065 725.51189104
 423.07852124  96.49849341 386.23881918 183.75701453 682.89308901
 628.71849712  91.35879797  83.48729975 716.97408346 270.12003998
 797.20772626 551.34032499 509.38215781 438.40194907 408.25712559
 133.47753342 214.91961102  85.99185295 533.32781628 590.00855425
 470.43899071 293.42214829 291.60912848 617.16311485 200.20062861
 488.72205947  85.55053494 507.36132449 790.57541774 564.14430673
 779.08473801 511.18087887 418.59934569  39.4601893  797.49773784
  96.25990177  72.60754058 305.12162193  93.95796203 220.91615462
 373.63722317  89.73512889  84.29906366 347.28895094 134.68810601
  81.1254455  247.65605604  91.09307803  90.65827339 716.04529702
 204.7849276  133.7199094  246.54284664  99.7093619  288.25966364
  75.99609

In [59]:
a = np.random.rand(100)*10
print(a)

[4.15602727 4.5690458  5.10067728 5.95265178 5.78257581 1.29667731
 2.99492829 4.13852779 9.14059177 1.20166846 7.66816396 3.82240183
 1.28646472 1.87838126 0.7525163  2.61127444 9.29863365 6.46402719
 9.18787325 9.02558723 1.45119119 1.43068874 9.50032786 6.49222817
 7.22852305 1.48955497 0.71671395 6.62264098 4.88096084 9.96014357
 4.35987861 0.08401859 9.03143204 3.47424144 3.93613076 8.49091748
 2.3610548  3.4257971  6.54049999 6.07103241 8.27959852 3.64836924
 2.00798178 9.81077496 3.21683234 9.41725671 4.45726208 1.62235586
 7.1417876  2.60029236 4.91788216 8.35535038 9.15190212 3.29053545
 4.15951534 1.80170918 5.26542367 9.59591921 1.44250491 7.31166232
 1.81599794 9.43807973 5.39824894 2.10687894 1.45097699 3.24747367
 6.39747553 7.94407839 9.87565457 7.07962971 4.65729439 4.50670284
 7.29024274 6.74668251 6.13660386 9.90532096 8.21770177 7.03239497
 9.60070284 2.7469277  7.75434414 9.58805555 0.03147867 9.72669963
 4.72962634 7.92630416 7.23606133 6.61324143 8.20907568 3.7472

In [60]:
aa =np.reshape(a,(2,10,5))
print(aa.shape)
print(np.min(aa))
print("____________")
print(np.min(aa , axis=2))

(2, 10, 5)
0.03147866608825267
____________
[[4.15602727 1.20166846 0.7525163  2.61127444 1.43068874 0.71671395
  0.08401859 2.3610548  2.00798178 1.62235586]
 [3.29053545 1.44250491 1.45097699 3.24747367 4.50670284 2.7469277
  0.03147867 3.74725066 1.17269796 1.33378204]]


In [61]:
print(aa)

[[[4.15602727 4.5690458  5.10067728 5.95265178 5.78257581]
  [1.29667731 2.99492829 4.13852779 9.14059177 1.20166846]
  [7.66816396 3.82240183 1.28646472 1.87838126 0.7525163 ]
  [2.61127444 9.29863365 6.46402719 9.18787325 9.02558723]
  [1.45119119 1.43068874 9.50032786 6.49222817 7.22852305]
  [1.48955497 0.71671395 6.62264098 4.88096084 9.96014357]
  [4.35987861 0.08401859 9.03143204 3.47424144 3.93613076]
  [8.49091748 2.3610548  3.4257971  6.54049999 6.07103241]
  [8.27959852 3.64836924 2.00798178 9.81077496 3.21683234]
  [9.41725671 4.45726208 1.62235586 7.1417876  2.60029236]]

 [[4.91788216 8.35535038 9.15190212 3.29053545 4.15951534]
  [1.80170918 5.26542367 9.59591921 1.44250491 7.31166232]
  [1.81599794 9.43807973 5.39824894 2.10687894 1.45097699]
  [3.24747367 6.39747553 7.94407839 9.87565457 7.07962971]
  [4.65729439 4.50670284 7.29024274 6.74668251 6.13660386]
  [9.90532096 8.21770177 7.03239497 9.60070284 2.7469277 ]
  [7.75434414 9.58805555 0.03147867 9.72669963 4.72962

In [62]:
print(np.max(a))

9.960143566447874


In [63]:
print(np.max(aa))
print(np.max(aa , axis=0))

9.960143566447874
[[4.91788216 8.35535038 9.15190212 5.95265178 5.78257581]
 [1.80170918 5.26542367 9.59591921 9.14059177 7.31166232]
 [7.66816396 9.43807973 5.39824894 2.10687894 1.45097699]
 [3.24747367 9.29863365 7.94407839 9.87565457 9.02558723]
 [4.65729439 4.50670284 9.50032786 6.74668251 7.22852305]
 [9.90532096 8.21770177 7.03239497 9.60070284 9.96014357]
 [7.75434414 9.58805555 9.03143204 9.72669963 4.72962634]
 [8.49091748 7.23606133 6.61324143 8.20907568 6.07103241]
 [8.27959852 4.90849513 6.79780826 9.81077496 7.14551462]
 [9.41725671 4.45726208 1.9378576  7.1417876  7.19484659]]


In [64]:
print(np.average(a))
print(np.average(aa))
print(np.average(aa , axis=0))

5.345628331922549
5.345628331922549
[[4.53695472 6.46219809 7.1262897  4.62159361 4.97104557]
 [1.54919324 4.13017598 6.8672235  5.29154834 4.25666539]
 [4.74208095 6.63024078 3.34235683 1.9926301  1.10174665]
 [2.92937406 7.84805459 7.20405279 9.53176391 8.05260847]
 [3.05424279 2.96869579 8.3952853  6.61945534 6.68256345]
 [5.69743797 4.46720786 6.82751797 7.24083184 6.35353563]
 [6.05711138 4.83603707 4.53145535 6.60047053 4.33287855]
 [8.20861082 4.79855807 5.01951926 7.37478783 4.90914154]
 [4.72614824 4.27843218 4.40289502 9.48793628 5.18117348]
 [5.37551937 4.33700529 1.78010673 4.65148892 4.89756947]]


___________________
متدهای آماری 
___________________

In [65]:
print(np.var(a))
print("_______________")
print(np.var(aa))
print("_______________")
print(np.var(aa , axis=2))

8.491986263952537
_______________
8.491986263952537
_______________
[[ 0.47303569  8.45845047  6.33604665  6.64354469 10.50734677 11.51322992
   8.18066785  4.88700196  9.41739535  8.30992645]
 [ 5.47572152  9.87734537  9.27405331  4.71399468  1.23718844  6.70479321
  13.28146453  2.55679802  7.26588544  4.60097295]]


In [66]:
print(np.std(a))
print("_______________")
print(np.std(aa))
print("_______________")
print(np.std(aa , axis=2))

2.9141012789456266
_______________
2.9141012789456266
_______________
[[0.6877759  2.90834153 2.5171505  2.57750746 3.24150378 3.39311508
  2.86018668 2.21065645 3.0687775  2.8826943 ]
 [2.34002597 3.14282443 3.04533304 2.17117357 1.11228973 2.58936154
  3.64437437 1.59899907 2.69553064 2.14498787]]


In [67]:
print(np.median(a))
print("_______________")
print(np.median(aa))
print("_______________")
print(np.median(aa , axis=2))

5.183050475017346
_______________
5.183050475017346
_______________
[[5.10067728 2.99492829 1.87838126 9.02558723 6.49222817 4.88096084
  3.93613076 6.07103241 3.64836924 4.45726208]
 [4.91788216 5.26542367 2.10687894 7.07962971 6.13660386 8.21770177
  7.75434414 7.23606133 6.79780826 2.16119024]]


In [68]:
print(np.mean(a))
print(np.mean(aa))
print(np.mean(aa , axis=0))

5.345628331922549
5.345628331922549
[[4.53695472 6.46219809 7.1262897  4.62159361 4.97104557]
 [1.54919324 4.13017598 6.8672235  5.29154834 4.25666539]
 [4.74208095 6.63024078 3.34235683 1.9926301  1.10174665]
 [2.92937406 7.84805459 7.20405279 9.53176391 8.05260847]
 [3.05424279 2.96869579 8.3952853  6.61945534 6.68256345]
 [5.69743797 4.46720786 6.82751797 7.24083184 6.35353563]
 [6.05711138 4.83603707 4.53145535 6.60047053 4.33287855]
 [8.20861082 4.79855807 5.01951926 7.37478783 4.90914154]
 [4.72614824 4.27843218 4.40289502 9.48793628 5.18117348]
 [5.37551937 4.33700529 1.78010673 4.65148892 4.89756947]]


In [69]:
a= np.arange(10)
print(a)
print(np.cumsum(a))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


In [70]:
abc = np.array([1 ,2 ,3 ,4 ,5, 5 ,5 , 6 , 1 ,3])
print(np.unique(abc))
print(np.unique(abc , return_index=True))

[1 2 3 4 5 6]
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 7], dtype=int64))


In [71]:
abc_string = np.array(['mohamad' , 'reza' , 'mohamad' , 'javad' , 'sadegh' , 'ali' , 'ali'])
print(np.unique(abc_string , return_index=True))

(array(['ali', 'javad', 'mohamad', 'reza', 'sadegh'], dtype='<U7'), array([5, 3, 0, 1, 4], dtype=int64))


In [72]:
print(np.sort(abc))

[1 1 2 3 3 4 5 5 5 6]


In [73]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('mohammad', 1.8, 32), ('alireza', 1.85, 34),
          ('ali', 1.98, 29),('siamak' , 1.79 , 31)]
a = np.array(values, dtype=dtype)
print(a)

[(b'mohammad', 1.8 , 32) (b'alireza', 1.85, 34) (b'ali', 1.98, 29)
 (b'siamak', 1.79, 31)]


In [74]:
print(np.sort(a , order='height'))
print('__________')
print(np.sort(a , order='age'))
print('__________')
print(np.sort(a , order=['age','height']))

[(b'siamak', 1.79, 31) (b'mohammad', 1.8 , 32) (b'alireza', 1.85, 34)
 (b'ali', 1.98, 29)]
__________
[(b'ali', 1.98, 29) (b'siamak', 1.79, 31) (b'mohammad', 1.8 , 32)
 (b'alireza', 1.85, 34)]
__________
[(b'ali', 1.98, 29) (b'siamak', 1.79, 31) (b'mohammad', 1.8 , 32)
 (b'alireza', 1.85, 34)]


In [59]:
a = np.random.randint(1,50, 10)
print(a)
print(-np.sort(-a))
print(np.sort(a))

[41  4 13  6 17  2 23  3 35 36]
[41 36 35 23 17 13  6  4  3  2]
[ 2  3  4  6 13 17 23 35 36 41]


In [75]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80])
b = np.array([10 , 40])
print(np.in1d(a , b))

[ True False False  True False False False False]


In [49]:
a= np.array(['siamak' ,'mohammad' , 'reza' , ' mohammad' , 'ali' , 'mohammad' , 'javad'])
b= np.array(['mohammad'])
print((np.in1d(a,b)))

[False  True False False False  True False]


In [77]:
np.save('test.npy',abc)

In [78]:
abc_load=np.load('test.npy')
print(abc_load)

[1 2 3 4 5 5 5 6 1 3]
